// {
//   id: "3",
//   name: "",
//   postal: "",
//   flag: "",
//   seal: "",
//   nickname: ["", ""],
//   dimensions: [
//     {
//       length: ["mi", "km"],
//       width: ["mi", "km"],
//     },
//   ],
//   motto: "",
//   website: "https://www. .gov/",
//   capital: "",
//   largestCity: "",
//   population: 731545,
//   totalAreaMI: 665384,
//   totalAreaKM: 1723337,
//   latitude: "",
//   longitude: "",
//   stateRouteMarker: "",
//   stateQuarter: "",
//   livingInsignia: [],
//   inanimateInsignia: [],
// },

export const states = [
  {
    id: "1",
    name: "Alabama",
    postal: "AL",
    flag:
      "https://upload.wikimedia.org/wikipedia/commons/5/5c/Flag_of_Alabama.svg",
    seal:
      "https://upload.wikimedia.org/wikipedia/commons/f/f7/Seal_of_Alabama.svg",
    nickname: [
      "The Yellowhammer State",
      "The Heart of Dixie",
      "The Cotton State",
    ],
    dimensions: [
      {
        length: ["330mi", "531km"],
        width: ["190mi", "305km"],
      },
    ],
    motto: "Audemus jura nostra defendere (We Dare Defend Our Rights)",
    website: "https://www.alabama.gov/",
    capital: "Montgomery",
    largestCity: "Birmingham",
    population: 4903185,
    totalAreaMI: 5242,
    totalAreaKM: 135767,
    latitude: "30°11' N to 35° N",
    longitude: "84°53' W to 88°28' W",
    stateRouteMarker:
      "https://upload.wikimedia.org/wikipedia/commons/5/57/Alabama_3.svg",
    stateQuarter:
      "https://upload.wikimedia.org/wikipedia/commons/a/a2/2003_AL_Proof.png",
    livingInsignia: [],
    inanimateInsignia: [],
  },
  {
    id: "2",
    name: "Alaska",
    postal: "AK",
    flag:
      "https://upload.wikimedia.org/wikipedia/commons/e/e6/Flag_of_Alaska.svg",
    seal:
      "https://upload.wikimedia.org/wikipedia/commons/9/96/State_Seal_of_Alaska.svg",
    nickname: ["The Last Frontier"],
    dimensions: [
      {
        length: ["1,420 mi", "2,285 km"],
        width: ["2,261 mi", "3,639 km"],
      },
    ],
    motto: "North to the Future",
    website: "https://www.alaska.gov/",
    capital: "Juneau",
    largestCity: "Anchorage",
    population: 731545,
    totalAreaMI: 665384,
    totalAreaKM: 1723337,
    latitude: "51°20'N to 71°50'N",
    longitude: "130°W to 172°E",
    stateRouteMarker:
      "https://upload.wikimedia.org/wikipedia/commons/1/12/Alaska_2_shield.svg",
    stateQuarter:
      "https://upload.wikimedia.org/wikipedia/commons/1/1f/2008_AK_Proof.png",
    livingInsignia: [],
    inanimateInsignia: [],
  },
  {
    id: "3",
    name: "Arizona",
    postal: "AZ",
    flag:
      "https://upload.wikimedia.org/wikipedia/commons/9/9d/Flag_of_Arizona.svg",
    seal:
      "https://upload.wikimedia.org/wikipedia/commons/7/7e/Arizona-StateSeal.svg",
    nickname: [
      "The Grand Canyon State",
      "The Copper State",
      "The Valentine State",
    ],
    dimensions: [
      {
        length: ["mi", "km"],
        width: ["mi", "km"],
      },
    ],
    motto: "Ditat Deus (God enriches)",
    website: "https://www.az.gov/",
    capital: "Phoenix",
    largestCity: "Phoenix",
    population: 7278717,
    totalAreaMI: 113990,
    totalAreaKM: 295234,
    latitude: "31°20′ N to 37° N",
    longitude: "109°03′ W to 114°49′ W",
    stateRouteMarker:
      "https://upload.wikimedia.org/wikipedia/commons/2/21/Arizona_87.svg",
    stateQuarter:
      "https://upload.wikimedia.org/wikipedia/commons/0/0e/2008_AZ_Proof.png",
    livingInsignia: [],
    inanimateInsignia: [],
  },
  {
    id: "4",
    name: "Arkansas",
    postal: "AR",
    flag:
      "https://upload.wikimedia.org/wikipedia/commons/9/9d/Flag_of_Arkansas.svg",
    seal:
      "https://upload.wikimedia.org/wikipedia/commons/a/a4/Seal_of_Arkansas.svg",
    nickname: ["The Natural State", "The Bear State"],
    dimensions: [
      {
        length: ["240 mi", "386 km"],
        width: ["270mi", "435km"],
      },
    ],
    motto: "Regnat populus (The People Rule)",
    website: "https://www.arkansas.gov/",
    capital: "Little Rock",
    largestCity: "Little Rock",
    population: 3017804,
    totalAreaMI: 53179,
    totalAreaKM: 137732,
    latitude: "33° 00′ N to 36° 30′ N",
    longitude: "89° 39′ W to 94° 37′ W",
    stateRouteMarker:
      "https://upload.wikimedia.org/wikipedia/commons/f/fe/Arkansas_1.svg",
    stateQuarter:
      "https://upload.wikimedia.org/wikipedia/commons/0/0c/2003_AR_Proof.png",
    livingInsignia: [],
    inanimateInsignia: [],
  },
  {
    id: "5",
    name: "California",
    postal: "CA",
    flag: "",
    seal: "",
    nickname: ["", ""],
    dimensions: [
      {
        length: ["mi", "km"],
        width: ["mi", "km"],
      },
    ],
    motto: "",
    website: "https://www. .gov/",
    capital: "",
    largestCity: "",
    population: 731545,
    totalAreaMI: 665384,
    totalAreaKM: 1723337,
    latitude: "",
    longitude: "",
    stateRouteMarker: "",
    stateQuarter: "",
    livingInsignia: [],
    inanimateInsignia: [],
  },
  {
    id: "6",
    name: "Colorado",
    postal: "CO",
    flag: "",
    seal: "",
    nickname: ["", ""],
    dimensions: [
      {
        length: ["mi", "km"],
        width: ["mi", "km"],
      },
    ],
    motto: "",
    website: "https://www. .gov/",
    capital: "",
    largestCity: "",
    population: 731545,
    totalAreaMI: 665384,
    totalAreaKM: 1723337,
    latitude: "",
    longitude: "",
    stateRouteMarker: "",
    stateQuarter: "",
    livingInsignia: [],
    inanimateInsignia: [],
  },
  {
    id: "7",
    name: "Connecticut",
    postal: "CT",
    flag: "",
    seal: "",
    nickname: ["", ""],
    dimensions: [
      {
        length: ["mi", "km"],
        width: ["mi", "km"],
      },
    ],
    motto: "",
    website: "https://www. .gov/",
    capital: "",
    largestCity: "",
    population: 731545,
    totalAreaMI: 665384,
    totalAreaKM: 1723337,
    latitude: "",
    longitude: "",
    stateRouteMarker: "",
    stateQuarter: "",
    livingInsignia: [],
    inanimateInsignia: [],
  },
  {
    id: "8",
    name: "Delaware",
    postal: "DE",
    flag: "",
    seal: "",
    nickname: ["", ""],
    dimensions: [
      {
        length: ["mi", "km"],
        width: ["mi", "km"],
      },
    ],
    motto: "",
    website: "https://www. .gov/",
    capital: "",
    largestCity: "",
    population: 731545,
    totalAreaMI: 665384,
    totalAreaKM: 1723337,
    latitude: "",
    longitude: "",
    stateRouteMarker: "",
    stateQuarter: "",
    livingInsignia: [],
    inanimateInsignia: [],
  },
  {
    id: "9",
    name: "Florida",
    postal: "FL",
    flag: "",
    seal: "",
    nickname: ["", ""],
    dimensions: [
      {
        length: ["mi", "km"],
        width: ["mi", "km"],
      },
    ],
    motto: "",
    website: "https://www. .gov/",
    capital: "",
    largestCity: "",
    population: 731545,
    totalAreaMI: 665384,
    totalAreaKM: 1723337,
    latitude: "",
    longitude: "",
    stateRouteMarker: "",
    stateQuarter: "",
    livingInsignia: [],
    inanimateInsignia: [],
  },
];
