// {
//   id: "3",
//   name: "",
//   postal: "",
// stateBorder: "",
//   flag: "",
//   seal: "",
//   nickname: ["", ""],
//   stateLength: [" mi", " km"],
//   stateWidth: [" mi", " km"],
//   motto: "",
//   website: "https://www. .gov/",
//   capital: "",
//   largestCity: "",
//   population: 731545,
//   totalAreaMI: 665384,
//   totalAreaKM: 1723337,
//   densityMI: 739,
//   densityKM: 285,
//   latitude: "",
//   longitude: "",
//   stateRouteMarker: "",
//   stateQuarter: "",
//   livingInsignia: [],
//   inanimateInsignia: [],
// },

export const states = [
  {
    id: "1",
    name: "Alabama",
    postal: "AL",
    stateBorder:
      "https://upload.wikimedia.org/wikipedia/commons/1/1a/Alabama_in_United_States.svg",
    flag:
      "https://upload.wikimedia.org/wikipedia/commons/5/5c/Flag_of_Alabama.svg",
    seal:
      "https://upload.wikimedia.org/wikipedia/commons/f/f7/Seal_of_Alabama.svg",
    nickname: [
      "The Yellowhammer State",
      "The Heart of Dixie",
      "The Cotton State",
    ],
    stateLength: ["330 mi", "531 km"],
    stateWidth: ["190 mi", "305 km"],
    motto: "Audemus jura nostra defendere (We Dare Defend Our Rights)",
    website: "https://www.alabama.gov/",
    capital: "Montgomery",
    largestCity: "Birmingham",
    population: 4903185,
    totalAreaMI: 5242,
    totalAreaKM: 135767,
    densityMI: 1,
    densityKM: 1,
    latitude: "30°11' N to 35° N",
    longitude: "84°53' W to 88°28' W",
    stateRouteMarker:
      "https://upload.wikimedia.org/wikipedia/commons/5/57/Alabama_3.svg",
    stateQuarter:
      "https://upload.wikimedia.org/wikipedia/commons/a/a2/2003_AL_Proof.png",
    livingInsignia: [],
    inanimateInsignia: [],
  },
  {
    id: "2",
    name: "Alaska",
    postal: "AK",
    stateBorder:
      "https://upload.wikimedia.org/wikipedia/commons/8/84/Alaska_in_United_States_%28US50%29.svg",
    flag:
      "https://upload.wikimedia.org/wikipedia/commons/e/e6/Flag_of_Alaska.svg",
    seal:
      "https://upload.wikimedia.org/wikipedia/commons/9/96/State_Seal_of_Alaska.svg",
    nickname: ["The Last Frontier"],
    stateLength: ["1,420 mi", "2,285 km"],
    stateWidth: ["2,261 mi", "3,639 km"],
    motto: "North to the Future",
    website: "https://www.alaska.gov/",
    capital: "Juneau",
    largestCity: "Anchorage",
    population: 731545,
    totalAreaMI: 665384,
    totalAreaKM: 1723337,
    densityMI: 1,
    densityKM: 1,
    latitude: "51°20'N to 71°50'N",
    longitude: "130°W to 172°E",
    stateRouteMarker:
      "https://upload.wikimedia.org/wikipedia/commons/1/12/Alaska_2_shield.svg",
    stateQuarter:
      "https://upload.wikimedia.org/wikipedia/commons/1/1f/2008_AK_Proof.png",
    livingInsignia: [],
    inanimateInsignia: [],
  },
  {
    id: "3",
    name: "Arizona",
    postal: "AZ",
    stateBorder:
      "https://upload.wikimedia.org/wikipedia/commons/d/d8/Arizona_in_United_States.svg",
    flag:
      "https://upload.wikimedia.org/wikipedia/commons/9/9d/Flag_of_Arizona.svg",
    seal:
      "https://upload.wikimedia.org/wikipedia/commons/7/7e/Arizona-StateSeal.svg",
    nickname: [
      "The Grand Canyon State",
      "The Copper State",
      "The Valentine State",
    ],
    stateLength: ["400 mi", "645 km"],
    stateWidth: ["310 mi", "500 km"],
    motto: "Ditat Deus (God enriches)",
    website: "https://www.az.gov/",
    capital: "Phoenix",
    largestCity: "Phoenix",
    population: 7278717,
    totalAreaMI: 113990,
    totalAreaKM: 295234,
    densityMI: 1,
    densityKM: 1,
    latitude: "31°20′ N to 37° N",
    longitude: "109°03′ W to 114°49′ W",
    stateRouteMarker:
      "https://upload.wikimedia.org/wikipedia/commons/2/21/Arizona_87.svg",
    stateQuarter:
      "https://upload.wikimedia.org/wikipedia/commons/0/0e/2008_AZ_Proof.png",
    livingInsignia: [
      { amphibian: "Arizona tree frog" },
      { bird: "Cactus wren" },
    ],
    inanimateInsignia: [],
  },
  {
    id: "4",
    name: "Arkansas",
    postal: "AR",
    stateBorder:
      "https://upload.wikimedia.org/wikipedia/commons/8/86/Arkansas_in_United_States.svg",
    flag:
      "https://upload.wikimedia.org/wikipedia/commons/9/9d/Flag_of_Arkansas.svg",
    seal:
      "https://upload.wikimedia.org/wikipedia/commons/a/a4/Seal_of_Arkansas.svg",
    nickname: ["The Natural State", "The Bear State"],
    stateLength: ["240 mi", "386 km"],
    stateWidth: ["270 mi", "435 km"],
    motto: "Regnat populus (The People Rule)",
    website: "https://www.arkansas.gov/",
    capital: "Little Rock",
    largestCity: "Little Rock",
    population: 3017804,
    totalAreaMI: 53179,
    totalAreaKM: 137732,
    densityMI: 1,
    densityKM: 1,
    latitude: "33° 00′ N to 36° 30′ N",
    longitude: "89° 39′ W to 94° 37′ W",
    stateRouteMarker:
      "https://upload.wikimedia.org/wikipedia/commons/f/fe/Arkansas_1.svg",
    stateQuarter:
      "https://upload.wikimedia.org/wikipedia/commons/0/0c/2003_AR_Proof.png",
    livingInsignia: [],
    inanimateInsignia: [],
  },
  {
    id: "5",
    name: "California",
    postal: "CA",
    stateBorder:
      "https://upload.wikimedia.org/wikipedia/commons/9/94/California_in_United_States.svg",
    flag:
      "https://upload.wikimedia.org/wikipedia/commons/0/01/Flag_of_California.svg",
    seal:
      "https://upload.wikimedia.org/wikipedia/en/a/ab/Great_Seal_of_California.svg",
    nickname: ["Golden State"],
    stateLength: ["770 mi", "1240 km"],
    stateWidth: ["250 mi", "400 km"],
    motto: "Eureka",
    website: "https://www.ca.gov/",
    capital: "Sacramento",
    largestCity: "Los Angeles",
    population: 39368078,
    totalAreaMI: 163696,
    totalAreaKM: 423970,
    densityMI: 1,
    densityKM: 1,
    latitude: "32°32′ N to 42° N",
    longitude: "114°8′ W to 124°26′ W",
    stateRouteMarker:
      "https://upload.wikimedia.org/wikipedia/commons/d/dd/California_1.svg",
    stateQuarter:
      "https://upload.wikimedia.org/wikipedia/commons/7/7d/2005_CA_Proof.png",
    livingInsignia: [],
    inanimateInsignia: [],
  },
  {
    id: "6",
    name: "Colorado",
    postal: "CO",
    stateBorder:
      "https://upload.wikimedia.org/wikipedia/commons/6/60/Colorado_in_United_States.svg",
    flag:
      "https://upload.wikimedia.org/wikipedia/commons/4/46/Flag_of_Colorado.svg",
    seal:
      "https://upload.wikimedia.org/wikipedia/commons/0/00/Seal_of_Colorado.svg",
    nickname: ["The Centennial State"],
    stateLength: ["380 mi", "610 km"],
    stateWidth: ["280 mi", "450 km"],
    motto: "Nil sine numine (Nothing without providence)",
    website: "https://www.colorado.gov/",
    capital: "Denver",
    largestCity: "Denver",
    population: 5758736,
    totalAreaMI: 104094,
    totalAreaKM: 269837,
    densityMI: 1,
    densityKM: 1,
    latitude: "37°N to 41°N",
    longitude: "102°02′48″W to 109°02′48″W",
    stateRouteMarker:
      "https://upload.wikimedia.org/wikipedia/commons/c/c0/Colorado_1.svg",
    stateQuarter:
      "https://upload.wikimedia.org/wikipedia/commons/9/90/2006_CO_Proof.png",
    livingInsignia: [],
    inanimateInsignia: [],
  },
  {
    id: "7",
    name: "Connecticut",
    postal: "CT",
    stateBorder:
      "https://upload.wikimedia.org/wikipedia/commons/3/3a/Connecticut_in_United_States_%28zoom%29.svg",
    flag:
      "https://upload.wikimedia.org/wikipedia/commons/9/96/Flag_of_Connecticut.svg",
    seal:
      "https://upload.wikimedia.org/wikipedia/commons/4/48/Seal_of_Connecticut.svg",
    nickname: [
      "The Constitution State",
      "The Nutmeg State",
      "The Provisions State",
      "The Land of Steady Habits",
    ],
    stateLength: ["70 mi", "113 km"],
    stateWidth: ["110 mi", "177 km"],
    motto: "Qui transtulit sustinet (He who transplanted still sustains)",
    website: "https://www.portal.ct.gov/",
    capital: "Hartford",
    largestCity: "Bridgeport",
    population: 3565287,
    totalAreaMI: 5567,
    totalAreaKM: 14357,
    densityMI: 739,
    densityKM: 285,
    latitude: "40°58′ N to 42°03′ N",
    longitude: "71°47′ W to 73°44′ W",
    stateRouteMarker:
      "https://upload.wikimedia.org/wikipedia/commons/5/5a/Connecticut_Highway_15.svg",
    stateQuarter:
      "https://upload.wikimedia.org/wikipedia/commons/f/fd/1999_CT_Proof.png",
    livingInsignia: [],
    inanimateInsignia: [],
  },
  {
    id: "8",
    name: "Delaware",
    postal: "DE",
    stateBorder:
      "https://upload.wikimedia.org/wikipedia/commons/8/8c/Delaware_in_United_States_%28zoom%29.svg",
    flag:
      "https://upload.wikimedia.org/wikipedia/commons/c/c6/Flag_of_Delaware.svg",
    seal:
      "https://upload.wikimedia.org/wikipedia/commons/3/35/Seal_of_Delaware.svg",
    nickname: [
      "The First State",
      "The Small Wonder",
      "Blue Hen State",
      "The Diamond State",
    ],
    stateLength: ["96 mi", "154 km"],
    stateWidth: ["30 mi", "48 km"],
    motto: "Liberty and Independence",
    website: "https://www.delaware.gov/",
    capital: "Dover",
    largestCity: "Wilmington",
    population: 973764,
    totalAreaMI: 248872,
    totalAreaKM: 6446,
    densityMI: 469,
    densityKM: 179,
    latitude: "38° 27′ N to 39° 50′ N",
    longitude: "75° 3′ W to 75° 47′ W",
    stateRouteMarker:
      "https://upload.wikimedia.org/wikipedia/commons/e/ec/Elongated_circle_1.svg",
    stateQuarter:
      "https://upload.wikimedia.org/wikipedia/commons/d/d4/1999_DE_Proof.png",
    livingInsignia: [],
    inanimateInsignia: [],
  },
  {
    id: "9",
    name: "Florida",
    postal: "FL",
    stateBorder:
      "https://upload.wikimedia.org/wikipedia/commons/1/15/Florida_in_United_States.svg",
    flag:
      "https://upload.wikimedia.org/wikipedia/commons/f/f7/Flag_of_Florida.svg",
    seal:
      "https://upload.wikimedia.org/wikipedia/commons/2/2b/Seal_of_Florida.svg",
    nickname: ["Sunshine State"],
    stateLength: ["447 mi", "721 km"],
    stateWidth: ["361 mi", "582 km"],
    motto: "In God We Trust",
    website: "https://www.myflorida.com/",
    capital: "Tallahassee",
    largestCity: "Jacksonville",
    population: 21733312,
    totalAreaMI: 6575770,
    totalAreaKM: 170312,
    densityMI: 384.3,
    densityKM: 121,
    latitude: "24° 27' N to 31° 00' N",
    longitude: "80° 02' W to 87° 38' W",
    stateRouteMarker:
      "https://upload.wikimedia.org/wikipedia/commons/3/39/Florida_27.svg",
    stateQuarter:
      "https://upload.wikimedia.org/wikipedia/commons/6/68/2004_FL_Proof.png",
    livingInsignia: [],
    inanimateInsignia: [],
  },
  {
    id: "10",
    name: "Georgia",
    postal: "GA",
    stateBorder:
      "https://upload.wikimedia.org/wikipedia/commons/d/d1/Georgia_in_United_States.svg",
    flag:
      "https://upload.wikimedia.org/wikipedia/commons/5/54/Flag_of_Georgia_%28U.S._state%29.svg",
    seal:
      "https://upload.wikimedia.org/wikipedia/commons/7/79/Seal_of_Georgia.svg",
    nickname: ["Peach State", "Empire State of the South"],
    stateLength: ["298 mi", "480 km"],
    stateWidth: ["230 mi", "370 km"],
    motto: "Wisdom, Justice, Moderation",
    website: "https://www.georgia.gov/",
    capital: "Atlanta",
    largestCity: "Atlanta",
    population: 10617423,
    totalAreaMI: 59425,
    totalAreaKM: 153910,
    densityMI: 165,
    densityKM: 65.4,
    latitude: "30.356–34.985° N",
    longitude: "80.840–85.605° W",
    stateRouteMarker:
      "https://upload.wikimedia.org/wikipedia/commons/d/d0/Georgia_8.svg",
    stateQuarter:
      "https://upload.wikimedia.org/wikipedia/commons/7/7d/1999_GA_Proof.png",
    livingInsignia: [],
    inanimateInsignia: [],
  },
  {
    id: "11",
    name: "Hawaii",
    postal: "HA",
    stateBorder:
      "https://upload.wikimedia.org/wikipedia/commons/4/48/Hawaii_in_United_States_%28zoom%29_%28US50%29_%28-grid%29.svg",
    flag:
      "https://upload.wikimedia.org/wikipedia/commons/e/ef/Flag_of_Hawaii.svg",
    seal:
      "https://upload.wikimedia.org/wikipedia/commons/c/ca/Seal_of_the_State_of_Hawaii.svg",
    nickname: [
      "The Aloha State",
      "Paradise of the Pacific",
      "The Islands of Aloha",
      "The 808 State",
    ],
    stateLength: ["1522 mi", "2450 km"],
    stateWidth: ["n/a mi", "n/a km"],
    motto:
      "Ua Mau ke Ea o ka ʻĀina i ka Pono (The Life of the Land Is Perpetuated in Righteousness)",
    website: "https://www.portal.ehawaii.gov/",
    capital: "Honolulu",
    largestCity: "Honolulu",
    population: 1415872,
    totalAreaMI: 10931,
    totalAreaKM: 28311,
    densityMI: 221,
    densityKM: 82.6,
    latitude: "18° 55′ N to 28° 27′ N",
    longitude: "154° 48′ W to 178° 22′ W",
    stateRouteMarker:
      "https://upload.wikimedia.org/wikipedia/commons/6/6e/HI-11.svg",
    stateQuarter:
      "https://upload.wikimedia.org/wikipedia/commons/a/af/2008_HI_Proof.png",
    livingInsignia: [],
    inanimateInsignia: [],
  },
];
